# Generated by Django 6.0.3 on 2026-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('classifier', 'Classifier'), ('regressor', 'Regressor'), ('recommendation', 'Recommendation'), ('forecasting', 'Forecasting'), ('other', 'Other')], default='other', max_length=20)),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
