# Generated by Django 6.0.3 on 2026-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('app', 'Authenticator App'), ('sms', 'SMS'), ('email', 'Email')], default='app', max_length=10)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_codes', models.JSONField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
